caterwaul.module( 'hijack' ,function($) {$.hijack=function( /* unary , node */options) {;
return(function( ) {var lex_table=function( /* unary , node */cs) {;
return(function( ) {var codes= (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (x.charCodeAt(0) ) ) ;
return xr} ) .call(this,cs.split( '' ) ) ;
return( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (codes.indexOf(x) !== -1) ) ;
return xr} ) .call(this, (function(i,u,s) {if( (u-i) *s<=0)return[ ] ;
for(var r= [ ] ,d=u-i;
d>0?i<u:i>u;
i+=s)r.push(i) ;
return r} ) ( (0) , (255) , (1) ) ) ) } ) .call(this) } ,hash=function( /* unary , node */xs) {;
return(function(o) {for(var r= { } ,i=0,l=o.length,x;
i<l;
 ++i)x=o[i] ,r[x[0] ] =x[1] ;
return r} ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( [x,true] ) ) ;
return xr} ) .call(this,xs) ) ) } ,default_tables= {lex_float: '.0123456789' ,lex_decimal: '0123456789' ,lex_integer: '0123456789abcdefABCDEFx' ,lex_exp: 'eE' ,lex_space: ' \n\t\r' ,lex_bracket: '()[]{}?:' ,lex_opener: '([{?:' ,lex_punct: '+-*/%&|^!~=<>?:;.,' ,lex_eol: '\n\r' ,lex_regexp_suffix: 'gims' ,lex_quote: '\'"/' ,lex_ident: '$_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789' } ,default_codes= {lex_slash: '/' ,lex_zero: '0' ,lex_star: '*' ,lex_back: '\\' ,lex_x: 'x' ,lex_dot: '.' ,lex_hash: '#' } ,operators=function( /* unary , node */options) {;
return(function( ) {var lex_op= (function(it) {return(hash(it) ) } ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push.apply(xr,Array.prototype.slice.call( (x.split( /\s+/ ) ) ) ) ;
return xr} ) .call(this,options.precedence) ) ) ,parse_reduce_order= (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (hash( /* unary , node */x.split( /\s+/ ) ) ) ) ;
return xr} ) .call(this,options.precedence) ,parse_associates_right=hash( /* unary , node */options.right.split( /\s+/ ) ) ,parse_lr=hash( /* unary , node */options.binary.split( /\s+/ ) ) ,parse_r=hash(options.prefix|| [ 'u+' , 'u-' , 'u!' , 'u~' , 'u++' , 'u--' , 'new' , 'typeof' , 'finally' , 'case' , 'var' , 'const' , 'void' , 'delete' ] ) ,parse_l=hash(options.postfix|| [ '--' , '++' ] ) ,lex_postfix_unary=parse_l,parse_invocation=hash(options.invocation|| [ '()' , '[]' ] ) ,parse_r_optional=hash(options.r_optional|| [ 'return' , 'throw' , 'break' , 'continue' , 'else' ] ) ,parse_ambiguous_group=hash(options.ambiguous_group|| [ '(' , '[' ] ) ,parse_block=hash(options.block|| [ ';' , '{' ] ) ,parse_ternary=hash(options.ternary|| [ /* unary , node */ '?' ] ) ,parse_not_a_value=hash(options.not_a_value|| [ 'function' , 'if' , 'for' , 'while' , 'catch' , 'void' , 'delete' , 'new' , 'typeof' , 'in' , 'instanceof' ] ) ,parse_also_expression=hash(options.also_expression|| [ /* unary , node */ 'function' ] ) ,parse_invisible=hash(options.invisible|| [ /* unary , node */ 'i;' ] ) ,parse_index_forward= (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( !parse_associates_right.hasOwnProperty( (function(it) {return(it[0] ) } ) .call(this, ( (function(o) {var ks= [ ] ;
for(var k in o)Object.prototype.hasOwnProperty.call(o,k) &&ks.push(k) ;
return ks} ) .call(this, (x) ) ) ) ) ) ) ;
return xr} ) .call(this,parse_reduce_order) ,parse_inverse_order= (function(o) {for(var r= { } ,i=0,l=o.length,x;
i<l;
 ++i)x=o[i] ,r[x[0] ] =x[1] ;
return r} ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push.apply(xr,Array.prototype.slice.call( ( (function(ops) {var op,op0,opi,opl,opr;
for(var opr=new ops.constructor() ,opi=0,opl=ops.length;
opi<opl;
 ++opi)op=ops[opi] ,opr.push( ( [op,xi] ) ) ;
return opr} ) .call(this, (function(o) {var ks= [ ] ;
for(var k in o)Object.prototype.hasOwnProperty.call(o,k) &&ks.push(k) ;
return ks} ) .call(this, (x) ) ) ) ) ) ;
return xr} ) .call(this,parse_reduce_order) ) ) ,parse_accepts=options.accepts|| { 'if' : 'else' , 'do' : 'while' , 'catch' : 'finally' , 'try' : 'catch' } ,parse_r_until_block= (function(xs) {var x,x0,xi,xl,xr;
var xr=new xs.constructor() ;
for(var k_b_5GnH$cA2Ct5xc6EBVTWqZF in xs)if(Object.prototype.hasOwnProperty.call(xs,k_b_5GnH$cA2Ct5xc6EBVTWqZF) )x=xs[k_b_5GnH$cA2Ct5xc6EBVTWqZF] ,xr[k_b_5GnH$cA2Ct5xc6EBVTWqZF] = ( +x) ;
return xr} ) .call(this, ( (options.blocks) || ( { 'function' : '2' , 'if' : '1' , 'do' : '1' , 'catch' : '1' , 'try' : '1' , 'for' : '1' , 'while' : '1' , 'with' : '1' , 'switch' : '1' } ) ) ) ,parse_group=options.group|| { '(' : ')' , '[' : ']' , '{' : '}' , '?' : ':' } ;
return( {lex_op:lex_op,parse_reduce_order:parse_reduce_order,parse_associates_right:parse_associates_right,parse_lr:parse_lr,parse_r:parse_r,parse_l:parse_l,lex_postfix_unary:lex_postfix_unary,parse_invocation:parse_invocation,parse_r_optional:parse_r_optional,parse_ambiguous_group:parse_ambiguous_group,parse_block:parse_block,parse_ternary:parse_ternary,parse_not_a_value:parse_not_a_value,parse_also_expression:parse_also_expression,parse_invisible:parse_invisible,parse_index_forward:parse_index_forward,parse_inverse_order:parse_inverse_order,parse_accepts:parse_accepts,parse_r_until_block:parse_r_until_block,parse_group:parse_group} ) } ) .call(this) } ,bindings_for=function( /* unary , node */options) {;
return $.merge( {caterwaul_global:$,map:$.map,empty:$.empty,has:function(o,k) {;
return Object.prototype.hasOwnProperty.call(o,k) } } , (function(xs) {var x,x0,xi,xl,xr;
var xr=new xs.constructor() ;
for(var k_b_5GnH$cA2Ct5xc6EBVTWqZF in xs)if(Object.prototype.hasOwnProperty.call(xs,k_b_5GnH$cA2Ct5xc6EBVTWqZF) )x=xs[k_b_5GnH$cA2Ct5xc6EBVTWqZF] ,xr[k_b_5GnH$cA2Ct5xc6EBVTWqZF] = ( (lex_table) .call( {x0:x0,xi:xi,xl:xl,xs:xs,xr:xr} ,x) ) ;
return xr} ) .call(this,$.merge( { } ,default_tables,options.tables) ) , (function(xs) {var x,x0,xi,xl,xr;
var xr=new xs.constructor() ;
for(var k_b_5GnH$cA2Ct5xc6EBVTWqZF in xs)if(Object.prototype.hasOwnProperty.call(xs,k_b_5GnH$cA2Ct5xc6EBVTWqZF) )x=xs[k_b_5GnH$cA2Ct5xc6EBVTWqZF] ,xr[k_b_5GnH$cA2Ct5xc6EBVTWqZF] = (x.charCodeAt(0) ) ;
return xr} ) .call(this,$.merge( { } ,default_codes,options.codes) ) ,operators(options) ) } ;
return( (function( ) {var bindings=bindings_for(options) ;
return( {parse:$.compile($.parse( /* unary , node */$.parse) ,bindings) ,serialize:$.compile($.parse( /* unary , node */$.javascript_tree_serialization_methods.serialize) ,bindings) } ) } ) .call(this) ) } ) .call(this) } } ) ;
